// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATiiDI2jOA7IdL4mS49SlksRu3o_vHcuY',
    appId: '1:434609326513:web:db5a910232667855e6d590',
    messagingSenderId: '434609326513',
    projectId: 'easy-recharge-app-78372',
    authDomain: 'easy-recharge-app-78372.firebaseapp.com',
    storageBucket: 'easy-recharge-app-78372.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF2NaQCl_wY1jMtfk7ynwdiepDHwUFAZ4',
    appId: '1:434609326513:android:5ca89258c1655ec9e6d590',
    messagingSenderId: '434609326513',
    projectId: 'easy-recharge-app-78372',
    storageBucket: 'easy-recharge-app-78372.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaVGqJ2LdhQjrM5cnQ42izDT24_Nwf-ZY',
    appId: '1:434609326513:ios:8a62c7bc67e5c492e6d590',
    messagingSenderId: '434609326513',
    projectId: 'easy-recharge-app-78372',
    storageBucket: 'easy-recharge-app-78372.firebasestorage.app',
    iosBundleId: 'com.example.easyRecharge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaVGqJ2LdhQjrM5cnQ42izDT24_Nwf-ZY',
    appId: '1:434609326513:ios:8a62c7bc67e5c492e6d590',
    messagingSenderId: '434609326513',
    projectId: 'easy-recharge-app-78372',
    storageBucket: 'easy-recharge-app-78372.firebasestorage.app',
    iosBundleId: 'com.example.easyRecharge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATiiDI2jOA7IdL4mS49SlksRu3o_vHcuY',
    appId: '1:434609326513:web:00f93b15b3eee5bfe6d590',
    messagingSenderId: '434609326513',
    projectId: 'easy-recharge-app-78372',
    authDomain: 'easy-recharge-app-78372.firebaseapp.com',
    storageBucket: 'easy-recharge-app-78372.firebasestorage.app',
  );
}
